### ISSUE TITLE
Email scripts and intake survey drafts

### ISSUE THREAD

**Issue by thin-lizard** [BITS-Research/GigPlatRevisit#10]
Hi Nic--

Here are the drafts of the recruitment [email scripts](https://docs.google.com/document/d/1qpzSzUIDS9pDWi1YedAjouj4cs7SFlkUtdxLEb0UlGg/edit) and [intake survey](https://docs.google.com/forms/d/15mkehdKJ2F-NzbGJCzzqoB9zIvkqZWcuInHSWr81C-Y/edit). I'm unsure at what point we send a consent form (and how that process works remotely overall). Please let me know what needs adjusting. Thanks!

**Comment by nniiicc** [comment]
I updated the survey with some tweaks to language ... 

The email script I collapsed into just one message - so that we are asking potential participants to fill out the survey if they are interested in participating. This will cut down on number of times you need to communicate with someone in order to enroll them in the study. 

A second email script should be used to enroll the person once they have agreed to participate - this should confirm a time, instruct the person how to connect for the interview, and provide an informed consent form - we can talk about this in more detail Monday. 

The other material is ready to send to participants.

**Comment by thin-lizard** [comment]
Hi Nic--

I've drafted the second [email](https://docs.google.com/document/d/1qpzSzUIDS9pDWi1YedAjouj4cs7SFlkUtdxLEb0UlGg/edit) for you to review. Thank you!

**Comment by nniiicc** [comment]
Made some edits - should be good now.
